# permissions for end users to view stubs.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: stub-viewer-role
rules:
- apiGroups:
  - test.cnrm.cloud.google.com
  resources:
  - stubs
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - test.cnrm.cloud.google.com
  resources:
  - stubs/status
  verbs:
  - get
